import type { Metadata } from "next";
import localFont from "next/font/local";
import SessionProviderWrapper from "@/provider/session";
import TrpcProviders from "@/provider/trpcProvider";
import ReactContextProvider from "@/provider/ReactContextProvider";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by Rashmi Barodiya",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <SessionProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-b from-cyan-200 via-gray-400 to-zinc-900`}
      >

        <SessionProviderWrapper >

          <TrpcProviders>
            <ReactContextProvider>
              {children}
            </ReactContextProvider>
          </TrpcProviders>

        </SessionProviderWrapper>

      </body>
    </html>
    // </SessionProvider>
  );
}
